services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command:
      redis-server --save 20 1 --loglevel warning --protected-mode no
      # --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data/redis
    networks:
      - apps

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - apps

  user:
    # Build image from current dir
    build: .
    ports:
      - 5111:5111
    #env_file: '.env'
    environment:
      - REDIS_URI=redis://redis:6379
      - MONGO_URI=mongodb://mongo:27017/axion
    networks:
      - apps
    links:
      - redis
      - mongo

volumes:
  cache:
    driver: local

networks:
  apps:
    driver: bridge
